services:
  web:
    build: ./FlaskApp
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      - MYSQL_USER = root
      - MYSQL_PASSWORD = 1234
      - MYSQL_DB = BucketList
      - MYSQL_HOST = db
  db:
    build: ./MySQL_Queries
    ports:
      - "3306:3306"
    environment:
      - MYSQL_PASSWORD = 1234

      