apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  namespace: ingress-nginx
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  hostPath:
    path: /tmp/data
    type: DirectoryOrCreate