- hosts: target
  become: yes
  remote_user: ubuntu
  become_user: root
  tasks:
  - name: Download Jenkins repo
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
    become: yes    

  - name: Ensure Repo is configured
    apt_repository: 
      repo: 'deb https://pkg.jenkins.io/debian-stable binary/' 
      state: present
    become: yes

  - name: Install pre-request
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - unzip
      - python3 
      - gnupg
      - lsb-release
  
  - name:  update apt
    apt:
      update_cache: 'yes'
      state: latest

  - name: Install java
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Add Docker GPG apt Key
    apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

  - name: Add Docker Repository
    apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

  - name: Update apt and install docker-ce
    apt:
        name: 
        - docker-ce
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
        state: latest
        update_cache: true
        
  - name: Install jenkins
    apt:
      name: jenkins
      state: latest
  - name: Install AWS cli url
    shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

  - name: Unarchieve AWS-cli.zip
    unarchive:
      src: awscliv2.zip
      dest: /home/ubuntu
      remote_src: yes

  - name: Install AWS cli
    shell: "./aws/install"    

  - name: Install Kubectl url
    shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  
  - name: install Kubectl
    shell: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    become: yes

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Make sure jenkins is started
    ansible.builtin.systemd:
      name: jenkins
      state: started

